apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# Pipeline tasks
- tekton/task-apply-manifest.yaml
- tekton/task-update-deployment.yaml

# Ansible task
- tekton/rbac.yaml
- tekton/task-ansible-runner.yaml
- tekton/pvc.yaml

# Pipeline
- tekton/pipeline.yaml

# Pipeline triggers
- tekton/trigger-template.yaml
- tekton/trigger-bindings.yaml
- tekton/event-listener.yaml
- tekton/trigger.yaml