apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vote-app
spec:
  serviceAccountName: pipeline
  triggers:
  # This is causing UI crush https://issues.redhat.com/browse/ODC-5350
  #   - triggerRef: vote-app
    - bindings:
        - kind: TriggerBinding
          ref: vote-app
      template:
        name: vote-app
